// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher@2.5.4_@types+node@22.19.6_@vue+compiler-sfc@3.5.26_cac@6.7._4fd495248b09a0dec13206298fd8180f/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher@2.5.4_@types+node@22.19.6_@vue+compiler-sfc@3.5.26_cac@6.7._4fd495248b09a0dec13206298fd8180f/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher@2.5.4_@types+node@22.19.6_@vue+compiler-sfc@3.5.26_cac@6.7._4fd495248b09a0dec13206298fd8180f/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher@2.5.4_@types+node@22.19.6_@vue+compiler-sfc@3.5.26_cac@6.7._4fd495248b09a0dec13206298fd8180f/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher@2.5.4_@types+node@22.19.6_@vue+compiler-sfc@3.5.26_cac@6.7._4fd495248b09a0dec13206298fd8180f/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher@2.5.4_@types+node@22.19.6_@vue+compiler-sfc@3.5.26_cac@6.7._4fd495248b09a0dec13206298fd8180f/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher@2.5.4_@types+node@22.19.6_@vue+compiler-sfc@3.5.26_cac@6.7._4fd495248b09a0dec13206298fd8180f/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher@2.5.4_@types+node@22.19.6_@vue+compiler-sfc@3.5.26_cac@6.7._4fd495248b09a0dec13206298fd8180f/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher@2.5.4_@types+node@22.19.6_@vue+compiler-sfc@3.5.26_cac@6.7._4fd495248b09a0dec13206298fd8180f/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher@2.5.4_@types+node@22.19.6_@vue+compiler-sfc@3.5.26_cac@6.7._4fd495248b09a0dec13206298fd8180f/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher@2.5.4_@types+node@22.19.6_@vue+compiler-sfc@3.5.26_cac@6.7._4fd495248b09a0dec13206298fd8180f/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@3.1.1_vite@7.3.1_@types+node@22.19.6_jiti@2.6.1_terser@5.44.1_yaml@2.8.2__vue@3.5.26_typescript@5.8.3_/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@3.1.1_vite@7.3.1_@types+node@22.19.6_jiti@2.6.1_terser@5.44.1_yaml@2.8.2__vue@3.5.26_typescript@5.8.3_/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@2.22.3_magicast@0.5.1_vite@7.3.1_@types+node@22.19.6_jiti@2.6.1_terser@5.44.1__9b04f5e130704c31fae8abed56f9984e/node_modules/@nuxt/ui/dist/runtime/plugins/slideovers.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@2.22.3_magicast@0.5.1_vite@7.3.1_@types+node@22.19.6_jiti@2.6.1_terser@5.44.1__9b04f5e130704c31fae8abed56f9984e/node_modules/@nuxt/ui/dist/runtime/plugins/modals.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@2.22.3_magicast@0.5.1_vite@7.3.1_@types+node@22.19.6_jiti@2.6.1_terser@5.44.1__9b04f5e130704c31fae8abed56f9984e/node_modules/@nuxt/ui/dist/runtime/plugins/colors.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.5.1/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.5.1/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+icon@1.15.0_magicast@0.5.1_vite@7.3.1_@types+node@22.19.6_jiti@2.6.1_terser@5.44._368477cf4b61ca85340c975be2ade799/node_modules/@nuxt/icon/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher@2.5.4_@types+node@22.19.6_@vue+compiler-sfc@3.5.26_cac@6.7._4fd495248b09a0dec13206298fd8180f/node_modules/nuxt/dist/app/plugins/warn.dev.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.20.2_@parcel+watcher@2.5.4_@types+node@22.19.6_@vue+compiler-sfc@3.5.26_cac@6.7._4fd495248b09a0dec13206298fd8180f/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'vue-devtools-client' | 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:browser-devtools-timing' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | '@nuxt/icon' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
